"""
Stacker: Level-1 Meta-Learner (The Umpire)

Uses XGBoost to learn cross-modality logic gates from the 
6-D Out-of-Fold prediction vectors generated by the specialized bags.
"""
import os
import pickle
import numpy as np
import xgboost as xgb
from datetime import datetime

class EnsembleStacker:
    def __init__(self, checkpoint_dir="checkpoints"):
        self.checkpoint_dir = checkpoint_dir
        os.makedirs(checkpoint_dir, exist_ok=True)
        
        # XGBoost classifier initialized to avoid overfitting minor dimensional spaces
        self.meta_model = xgb.XGBClassifier(
            n_estimators=100,
            learning_rate=0.05,
            max_depth=3,
            random_state=42,
            eval_metric="auc"
        )
        
    def fit(self, X_train, y_train):
        """
        X_train: (N, 6) feature vectors.
        [RGB_PC, RGB_SN, IR_PC, IR_SN, Concat_PC, Concat_SN]
        y_train: (N,) binary labels (0 = nominal, 1 = anomaly)
        """
        print(f"Training XGBoost Meta-Learner on {X_train.shape[0]} OOF vector samples...")
        self.meta_model.fit(X_train, y_train)
        print("Meta-Learner training complete.")
        
    def predict_proba(self, X_test):
        """
        Returns the probability of the positive class (anomaly).
        """
        probas = self.meta_model.predict_proba(X_test)
        return probas[:, 1]
        
    def predict(self, X_test):
        return self.meta_model.predict(X_test)
        
    def save(self, run_name=None):
        if run_name is None:
            run_name = datetime.now().strftime("%Y%m%d_%H%M%S")
        filepath = os.path.join(self.checkpoint_dir, f"stacker_xgb_{run_name}.pkl")
        with open(filepath, 'wb') as f:
            pickle.dump(self.meta_model, f)
        print(f"Stacker logic array serialized to {filepath}")
        
    def load(self, filepath):
        with open(filepath, 'rb') as f:
            self.meta_model = pickle.load(f)
        print(f"Stacker logic loaded from {filepath}")
